name: QA

on:
    push:
    pull_request:

jobs:
    qa:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                shopware: [ "6.7.*" ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "8.2"
                    coverage: none

            -   name: Configure Composer auth
                env:
                    SHOPWARE_PACKAGES_TOKEN: ${{ secrets.SHOPWARE_PACKAGES_TOKEN }}
                    GH_TOKEN_COMPOSER: ${{ secrets.GH_TOKEN_COMPOSER }}
                run: |
                    composer config --global --auth bearer.packages.shopware.com "$SHOPWARE_PACKAGES_TOKEN"
                    if [ -n "$GITHUB_TOKEN_COMPOSER" ]; then
                      composer config --global --auth github-oauth.github.com "$GH_TOKEN_COMPOSER"
                    fi

            -   name: Install dependencies
                run: |
                    composer require shopware/core:${{ matrix.shopware }} --no-interaction --prefer-dist --no-progress --prefer-stable
                    ./install.sh

            -   name: Run QA checks
                run: composer pre-commit
